### PR TITLE
Update script.js

### LINKED ISSUE #12: Add JS code in a seperate file
It is not considered a good practice to add scripts to the HTML file. Recommend to create a separate file for the JS

style in html

### PR DESCRIPTION
**Pull request by ManuSquall**
Add a changing theme listener on how the preference is set in the browser related to schmelto suggestion in issue #9

### CODE REVIEW

**Review by chryzcode — COMMENTED** [review]
@namangupta1399 @jomefavourite @Evavic44 please review this

**Review by namangupta1399 — APPROVED** [review]
Nice addition @ManuSquall 

LGTM 👍

**Review by Evavic44 — APPROVED** [review]
LGTM. 💯

**Comment by namangupta1399** [comment]
Sorry @jomefavourite , I forgot to wait for your review

**Comment by jomefavourite** [comment]
> Sorry @jomefavourite , I forgot to wait for your review

No problem 👍

**Review by jomefavourite — APPROVED** [review]

**Pull request merged**
